import type { EventCard } from '@aventi/contracts';

export const sampleEvents: EventCard[] = [
  {
    id: 'evt-1',
    title: 'Neon Terrace Session',
    description: 'Late-night rooftop set with deep house and skyline views.',
    category: 'nightlife',
    venueName: 'Aster Roof',
    city: 'Austin',
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 5).toISOString(),
    endsAt: null,
    bookingUrl: 'https://example.com/events/neon-terrace',
    imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1200&q=80',
    priceLabel: '$25',
    isFree: false,
    radiusMiles: 4.2,
    vibes: ['energetic', 'luxury', 'late-night', 'social'],
    tags: ['rooftop', 'house', 'dj'],
  },
  {
    id: 'evt-2',
    title: 'Candlelight Sound Bath',
    description: 'Immersive guided reset with crystal bowls and tea.',
    category: 'wellness',
    venueName: 'The Quiet Room',
    city: 'Austin',
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 18).toISOString(),
    endsAt: null,
    bookingUrl: 'https://example.com/events/sound-bath',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80',
    priceLabel: '$35',
    isFree: false,
    radiusMiles: 2.3,
    vibes: ['chill', 'wellness', 'luxury'],
    tags: ['sound bath', 'meditation'],
  },
  {
    id: 'evt-3',
    title: 'Warehouse Indie Night',
    description: 'Three local indie bands and a post-show vinyl afterparty.',
    category: 'concerts',
    venueName: 'Southline Works',
    city: 'Austin',
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 30).toISOString(),
    endsAt: null,
    bookingUrl: 'https://example.com/events/warehouse-indie-night',
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=80',
    priceLabel: '$18',
    isFree: false,
    radiusMiles: 5.0,
    vibes: ['live-music', 'energetic', 'social'],
    tags: ['indie rock', 'vinyl'],
  },
];
